/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CreateReservationResult = { 'ok' : ReservationId } |
  { 'err' : string };
export interface Reservation {
  'id' : ReservationId,
  'status' : ReservationStatus,
  'depositAmount' : bigint,
  'checkIn' : bigint,
  'createdAt' : bigint,
  'rejectionReason' : [] | [string],
  'guestName' : string,
  'guestEmail' : string,
  'numGuests' : bigint,
  'totalAmount' : bigint,
  'checkOut' : bigint,
  'stripePaymentIntentId' : [] | [string],
  'guestPhone' : string,
  'roomId' : RoomId,
  'depositPaid' : boolean,
}
export type ReservationId = bigint;
export type ReservationStatus = { 'Confirmed' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface Room {
  'id' : RoomId,
  'bedType' : string,
  'imageUrls' : Array<string>,
  'nightlyRate' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'amenities' : Array<string>,
  'capacity' : bigint,
}
export type RoomId = bigint;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAvailability' : ActorMethod<[RoomId, bigint, bigint], boolean>,
  'confirmReservation' : ActorMethod<[ReservationId], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createDepositPaymentIntent' : ActorMethod<
    [ReservationId],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createReservation' : ActorMethod<
    [string, string, string, RoomId, bigint, bigint, bigint],
    CreateReservationResult
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getReservation' : ActorMethod<[ReservationId], [] | [Reservation]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listReservations' : ActorMethod<[], Array<Reservation>>,
  'listRooms' : ActorMethod<[], Array<Room>>,
  'recordDepositPaid' : ActorMethod<[ReservationId, string], undefined>,
  'rejectReservation' : ActorMethod<[ReservationId, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];