/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoomId = IDL.Nat;
export const ReservationId = IDL.Nat;
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CreateReservationResult = IDL.Variant({
  'ok' : ReservationId,
  'err' : IDL.Text,
});
export const ReservationStatus = IDL.Variant({
  'Confirmed' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Reservation = IDL.Record({
  'id' : ReservationId,
  'status' : ReservationStatus,
  'depositAmount' : IDL.Nat,
  'checkIn' : IDL.Int,
  'createdAt' : IDL.Int,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'guestName' : IDL.Text,
  'guestEmail' : IDL.Text,
  'numGuests' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'checkOut' : IDL.Int,
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'guestPhone' : IDL.Text,
  'roomId' : RoomId,
  'depositPaid' : IDL.Bool,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Room = IDL.Record({
  'id' : RoomId,
  'bedType' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'nightlyRate' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'capacity' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAvailability' : IDL.Func(
      [RoomId, IDL.Int, IDL.Int],
      [IDL.Bool],
      ['query'],
    ),
  'confirmReservation' : IDL.Func([ReservationId], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDepositPaymentIntent' : IDL.Func(
      [ReservationId],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createReservation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, RoomId, IDL.Int, IDL.Int, IDL.Nat],
      [CreateReservationResult],
      [],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReservation' : IDL.Func(
      [ReservationId],
      [IDL.Opt(Reservation)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'listRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'recordDepositPaid' : IDL.Func([ReservationId, IDL.Text], [], []),
  'rejectReservation' : IDL.Func([ReservationId, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoomId = IDL.Nat;
  const ReservationId = IDL.Nat;
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CreateReservationResult = IDL.Variant({
    'ok' : ReservationId,
    'err' : IDL.Text,
  });
  const ReservationStatus = IDL.Variant({
    'Confirmed' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Reservation = IDL.Record({
    'id' : ReservationId,
    'status' : ReservationStatus,
    'depositAmount' : IDL.Nat,
    'checkIn' : IDL.Int,
    'createdAt' : IDL.Int,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'guestName' : IDL.Text,
    'guestEmail' : IDL.Text,
    'numGuests' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'checkOut' : IDL.Int,
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'guestPhone' : IDL.Text,
    'roomId' : RoomId,
    'depositPaid' : IDL.Bool,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Room = IDL.Record({
    'id' : RoomId,
    'bedType' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'nightlyRate' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'capacity' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAvailability' : IDL.Func(
        [RoomId, IDL.Int, IDL.Int],
        [IDL.Bool],
        ['query'],
      ),
    'confirmReservation' : IDL.Func([ReservationId], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDepositPaymentIntent' : IDL.Func(
        [ReservationId],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createReservation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, RoomId, IDL.Int, IDL.Int, IDL.Nat],
        [CreateReservationResult],
        [],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReservation' : IDL.Func(
        [ReservationId],
        [IDL.Opt(Reservation)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'listRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'recordDepositPaid' : IDL.Func([ReservationId, IDL.Text], [], []),
    'rejectReservation' : IDL.Func([ReservationId, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };